In [46]:
import pandas as pd
from nltk.tokenize import word_tokenize
import nltk
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MultiLabelBinarizer
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/smillafox/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [4]:
df = pd.read_csv("answerList_data.csv")

In [5]:
df.head()

,Answer.ID,FailingMethod,Question.ID,Answer.duration,Answer.confidence,Answer.difficulty,GroundTruth,TP,TN,FN,...,Code.complexity,Worker.ID,Worker.score,Worker.profession,Worker.yearsOfExperience,Worker.age,Worker.gender,Worker.whereLearnedToCode,Worker.country,Worker.programmingLanguage
0,261,HIT01_8,0,90.984,4,2,0,0,1,0,...,1,832cg-7G1i-462:73eI-8E-2g-985,5,Undergraduate_Student,7.0,21,Male,High School,United States,Java; C++; C#
1,262,HIT01_8,0,133.711,5,1,0,0,1,0,...,1,98ce7A-4i-507,4,Undergraduate_Student,10.0,25,Female,High School;University;Web,United States,c#
2,263,HIT01_8,0,77.696,5,2,0,0,1,0,...,1,881AC0I2E-625:135cI3E-7e8-86,5,Professional_Developer,7.0,24,Male,High School;University;Web,United States,C++;Java;PHP
3,264,HIT01_8,0,46.644,1,1,0,0,1,0,...,1,270eG-5c6A3-46:65eI-2i-2I-9-36,5,Professional_Developer,20.0,38,Male,High School;University;Other On the job,USA,C#
4,265,HIT01_8,0,215.416,5,5,0,0,1,0,...,1,844Cg1g5e1-17:255ei-8G8E85-8,3,Undergraduate_Student,5.0,19,Male,High School;University;Web,United States,C++; Java

In [6]:
df.columns

Index(['Answer.ID', 'FailingMethod', 'Question.ID', 'Answer.duration',
       'Answer.confidence', 'Answer.difficulty', 'GroundTruth', 'TP', 'TN',
       'FN', 'FP', 'Answer.option', 'Answer.order', 'Answer.explanation',
       'Code.LOC', 'Code.complexity', 'Worker.ID', 'Worker.score',
       'Worker.profession', 'Worker.yearsOfExperience', 'Worker.age',
       'Worker.gender', 'Worker.whereLearnedToCode', 'Worker.country',
       'Worker.programmingLanguage'],
      dtype='object')

In [7]:
df.shape

(2580, 25)

## Complexity Score
- TTR: how many unique words are used, affected by length (number of types/number of tokens)
- Halstead volume: for code

In [127]:
explanations = list(df["Answer.explanation"])
explanations = [str(e) for e in explanations]
scores = [len(list(set(word_tokenize(e)))) / len(word_tokenize(e)) for e in explanations]

In [128]:
df.loc[:, "TTR"] = scores

In [129]:
df.head()

,Answer.ID,FailingMethod,Question.ID,Answer.duration,Answer.confidence,Answer.difficulty,GroundTruth,TP,TN,FN,...,Worker.ID,Worker.score,Worker.profession,Worker.yearsOfExperience,Worker.age,Worker.gender,Worker.whereLearnedToCode,Worker.country,Worker.programmingLanguage,TTR
0,261,HIT01_8,0,90.984,4,2,0,0,1,0,...,832cg-7G1i-462:73eI-8E-2g-985,5,Undergraduate_Student,7.0,21,Male,High School,United States,Java; C++; C#,0.888889
1,262,HIT01_8,0,133.711,5,1,0,0,1,0,...,98ce7A-4i-507,4,Undergraduate_Student,10.0,25,Female,High School;University;Web,United States,c#,0.923077
2,263,HIT01_8,0,77.696,5,2,0,0,1,0,...,881AC0I2E-625:135cI3E-7e8-86,5,Professional_Developer,7.0,24,Male,High School;University;Web,United States,C++;Java;PHP,0.777778
3,264,HIT01_8,0,46.644,1,1,0,0,1,0,...,270eG-5c6A3-46:65eI-2i-2I-9-36,5,Professional_Developer,20.0,38,Male,High School;University;Other On the job,USA,C#,1.000000
4,265,HIT01_8,0,215.416,5,5,0,0,1,0,...,844Cg1g5e1-17:255ei-8G8E85-8,3,Undergraduate_Student,5.0,19,Male,High School;University;Web,United States,C++; Java,0.947368

In [178]:
features = [ "GroundTruth", "FailingMethod", 'Answer.duration','Answer.confidence', 'Answer.difficulty','Answer.option', 'Answer.order',
       'Code.LOC', 'Code.complexity', 'Worker.score',
       'Worker.profession', 'Worker.yearsOfExperience', 'Worker.age',
       'Worker.gender', 'Worker.whereLearnedToCode', 'Worker.country',
       'Worker.programmingLanguage', 'TTR']

In [179]:
filtered_data = df.loc[:, features]
filtered_data["Worker.whereLearnedToCode"] = filtered_data["Worker.whereLearnedToCode"].apply(lambda a: a.split(";"))
filtered_data

,GroundTruth,FailingMethod,Answer.duration,Answer.confidence,Answer.difficulty,Answer.option,Answer.order,Code.LOC,Code.complexity,Worker.score,Worker.profession,Worker.yearsOfExperience,Worker.age,Worker.gender,Worker.whereLearnedToCode,Worker.country,Worker.programmingLanguage,TTR
0,0,HIT01_8,90.984,4,2,NO,3,1,1,5,Undergraduate_Student,7.0,21,Male,[High School],United States,Java; C++; C#,0.888889
1,0,HIT01_8,133.711,5,1,NO,3,1,1,4,Undergraduate_Student,10.0,25,Female,"[High School, University, Web]",United States,c#,0.923077
2,0,HIT01_8,77.696,5,2,NO,3,1,1,5,Professional_Developer,7.0,24,Male,"[High School, University, Web]",United States,C++;Java;PHP,0.777778
3,0,HIT01_8,46.644,1,1,NO,3,1,1,5,Professional_Developer,20.0,38,Male,"[High School, University, Other On the job]",USA,C#,1.000000
4,0,HIT01_8,215.416,5,5,NO,3,1,1,3,Undergraduate_Student,5.0,19,Male,"[High School, University, Web]",United States,C++; Java,0.947368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,0,HIT08_54,220.420,2,4,NO,1,1,1,3,Graduate_Student,2.0,28,Male,[University],USA,C#,0.800000
2576,0,HIT08_54,322.790,4,3,YES,1,1,1,5,Professional_Developer,17.0,39,Male,"[University, Web]",USA,C#; VB.NET; Java,0.900000
2577,0,HIT08_54,159.530,5,1,NO,1,1,1,4,Professional_Developer,10.0,31,Male,"[High School, University, Web, Other work]",usa,C++,1.000000
2578,0,HIT08_54,68.578,5,1,NO,1,1,1,4,Undergraduate_Student,4.0,19,Male,"[University, Web, Other FIRST Robotics]",United States,C++,1.000000
2579,0,HIT08_54,72.605,4,4,NO,2,1,1,5,Graduate_Student,3.0,24,Male,"[University, Web]",India,Java,0.842105

In [180]:
mlb = MultiLabelBinarizer()
whereLearnedToCodeVector = mlb.fit_transform(filtered_data.loc[:, "Worker.whereLearnedToCode"])
whereLearnedToCodeVector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 1]])

In [181]:
mlb.classes_

array([' books', ' no?',
       ' there was no "internet". I had a TRS-80 for gosh sake. We learned from books! Made of paper. Odd concept',
       'High School', 'Other', 'Other Books', 'Other Diploma',
       'Other Employer', 'Other FIRST Robotics', 'Other Hobby',
       'Other Hobbyist', 'Other Instructional books',
       'Other Java while on the job',
       'Other Leanred more experts at work', 'Other MOOC',
       'Other Middle school', 'Other On the job',
       'Other Private Institute', 'Other Professional',
       'Other Professionally', 'Other Self Help Books',
       'Other Self Study', 'Other Self Taught', 'Other Self taught',
       'Other Self-study', 'Other Self-taught as a child',
       'Other Summer Camp', 'Other Taught myself the basics as a kid',
       'Other Through work', 'Other Training classes', 'Other US Army',
       'Other When I started programming (At age 9)', 'Other Work',
       'Other as long as i can remember honestly', 'Other at work',
       'Other autodidact', 'Other books', 'Other by myself from books',
       'Other elementary school', 'Other forever', 'Other found a book',
       'Other had a book on BASIC when I was a kid',
       'Other i really dont remember a time when i couldnt',
       'Other junior high computer class', 'Other na', 'Other on the job',
       'Other private', 'Other private institute', 'Other self study',
       'Other self taught', 'Other self-taught', 'Other work',
       'University', 'Web'], dtype=object)

In [182]:
whereLearnedToCodeDf = pd.DataFrame(whereLearnedToCodeVector, columns=mlb.classes_)
data = pd.concat([filtered_data, whereLearnedToCodeDf], axis=1)

In [183]:
data

,GroundTruth,FailingMethod,Answer.duration,Answer.confidence,Answer.difficulty,Answer.option,Answer.order,Code.LOC,Code.complexity,Worker.score,...,Other na,Other on the job,Other private,Other private institute,Other self study,Other self taught,Other self-taught,Other work,University,Web
0,0,HIT01_8,90.984,4,2,NO,3,1,1,5,...,0,0,0,0,0,0,0,0,0,0
1,0,HIT01_8,133.711,5,1,NO,3,1,1,4,...,0,0,0,0,0,0,0,0,1,1
2,0,HIT01_8,77.696,5,2,NO,3,1,1,5,...,0,0,0,0,0,0,0,0,1,1
3,0,HIT01_8,46.644,1,1,NO,3,1,1,5,...,0,0,0,0,0,0,0,0,1,0
4,0,HIT01_8,215.416,5,5,NO,3,1,1,3,...,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,0,HIT08_54,220.420,2,4,NO,1,1,1,3,...,0,0,0,0,0,0,0,0,1,0
2576,0,HIT08_54,322.790,4,3,YES,1,1,1,5,...,0,0,0,0,0,0,0,0,1,1
2577,0,HIT08_54,159.530,5,1,NO,1,1,1,4,...,0,0,0,0,0,0,0,1,1,1
2578,0,HIT08_54,68.578,5,1,NO,1,1,1,4,...,0,0,0,0,0,0,0,0,1,1
2579,0,HIT08_54,72.605,4,4,NO,2,1,1,5,...,0,0,0,0,0,0,0,0,1,1

In [184]:
data["Worker.programmingLanguage"]

0          Java; C++; C#
1                     c#
2           C++;Java;PHP
3                     C#
4              C++; Java
              ...
2575                  C#
2576    C#; VB.NET; Java
2577                 C++
2578                 C++
2579                Java
Name: Worker.programmingLanguage, Length: 2580, dtype: object

In [185]:
data["Worker.programmingLanguage"] = data["Worker.programmingLanguage"].apply(lambda a: str(a).split(";"))
data

,GroundTruth,FailingMethod,Answer.duration,Answer.confidence,Answer.difficulty,Answer.option,Answer.order,Code.LOC,Code.complexity,Worker.score,...,Other na,Other on the job,Other private,Other private institute,Other self study,Other self taught,Other self-taught,Other work,University,Web
0,0,HIT01_8,90.984,4,2,NO,3,1,1,5,...,0,0,0,0,0,0,0,0,0,0
1,0,HIT01_8,133.711,5,1,NO,3,1,1,4,...,0,0,0,0,0,0,0,0,1,1
2,0,HIT01_8,77.696,5,2,NO,3,1,1,5,...,0,0,0,0,0,0,0,0,1,1
3,0,HIT01_8,46.644,1,1,NO,3,1,1,5,...,0,0,0,0,0,0,0,0,1,0
4,0,HIT01_8,215.416,5,5,NO,3,1,1,3,...,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,0,HIT08_54,220.420,2,4,NO,1,1,1,3,...,0,0,0,0,0,0,0,0,1,0
2576,0,HIT08_54,322.790,4,3,YES,1,1,1,5,...,0,0,0,0,0,0,0,0,1,1
2577,0,HIT08_54,159.530,5,1,NO,1,1,1,4,...,0,0,0,0,0,0,0,1,1,1
2578,0,HIT08_54,68.578,5,1,NO,1,1,1,4,...,0,0,0,0,0,0,0,0,1,1
2579,0,HIT08_54,72.605,4,4,NO,2,1,1,5,...,0,0,0,0,0,0,0,0,1,1

In [186]:
mlb = MultiLabelBinarizer()
languagesVector = mlb.fit_transform(data.loc[:, "Worker.programmingLanguage"])

In [187]:
languagesDf = pd.DataFrame(languagesVector, columns=mlb.classes_)
data = pd.concat([data, languagesDf], axis=1)

In [188]:
data.columns

Index(['GroundTruth', 'FailingMethod', 'Answer.duration', 'Answer.confidence',
       'Answer.difficulty', 'Answer.option', 'Answer.order', 'Code.LOC',
       'Code.complexity', 'Worker.score',
       ...
       'php', 'php and C++', 'python', 'ruby', 'tera data', 'vb .net java',
       'vb.net', 'vbs', 'visual fox pro', 'visual foxpro'],
      dtype='object', length=215)

In [189]:
data.drop(["Worker.programmingLanguage", "Worker.whereLearnedToCode"], inplace=True, axis=1)
data.columns

Index(['GroundTruth', 'FailingMethod', 'Answer.duration', 'Answer.confidence',
       'Answer.difficulty', 'Answer.option', 'Answer.order', 'Code.LOC',
       'Code.complexity', 'Worker.score',
       ...
       'php', 'php and C++', 'python', 'ruby', 'tera data', 'vb .net java',
       'vb.net', 'vbs', 'visual fox pro', 'visual foxpro'],
      dtype='object', length=213)

In [190]:
categorical_data = data.select_dtypes(include=['object', 'category'])
numerical_data = data.select_dtypes(include=['number'])

label_encoded_data = categorical_data.apply(LabelEncoder().fit_transform)

combined_data = pd.concat([numerical_data, label_encoded_data], axis=1)

In [191]:
set(combined_data.columns) == set(data.columns)

True

In [192]:
combined_data.head()

,GroundTruth,Answer.duration,Answer.confidence,Answer.difficulty,Answer.order,Code.LOC,Code.complexity,Worker.score,Worker.yearsOfExperience,Worker.age,...,vb .net java,vb.net,vbs,visual fox pro,visual foxpro,FailingMethod,Answer.option,Worker.profession,Worker.gender,Worker.country
0,0,90.984,4,2,3,1,1,5,7.0,21,...,0,0,0,0,0,0,1,4,1,22
1,0,133.711,5,1,3,1,1,4,10.0,25,...,0,0,0,0,0,0,1,4,0,22
2,0,77.696,5,2,3,1,1,5,7.0,24,...,0,0,0,0,0,0,1,3,1,22
3,0,46.644,1,1,3,1,1,5,20.0,38,...,0,0,0,0,0,0,1,3,1,21
4,0,215.416,5,5,3,1,1,3,5.0,19,...,0,0,0,0,0,0,1,4,1,22

## Split

In [193]:
bug_reports = list(set(combined_data["FailingMethod"]))
print(bug_reports)
test_set_reports = bug_reports[:2]
training_set_reports = bug_reports[2:]
test_set_reports

[0, 1, 2, 3, 4, 5, 6, 7]

[0, 1]

In [194]:
train_set = combined_data.loc[combined_data["FailingMethod"].isin(training_set_reports)]
test_set = combined_data.loc[combined_data["FailingMethod"].isin(test_set_reports)]
train_set.shape

(2260, 213)

In [195]:
test_set.shape

(320, 213)

## Fit Classifier

In [201]:
y_train = train_set["GroundTruth"]
y_test = test_set["GroundTruth"]
y_train

320     0
321     0
322     0
323     0
324     0
       ..
2575    0
2576    0
2577    0
2578    0
2579    0
Name: GroundTruth, Length: 2260, dtype: int64

In [203]:
X_train = train_set.drop(["GroundTruth", "FailingMethod"], axis=1)
X_test = test_set.drop(["GroundTruth", "FailingMethod"], axis=1)
X_train

,Answer.duration,Answer.confidence,Answer.difficulty,Answer.order,Code.LOC,Code.complexity,Worker.score,Worker.yearsOfExperience,Worker.age,TTR,...,tera data,vb .net java,vb.net,vbs,visual fox pro,visual foxpro,Answer.option,Worker.profession,Worker.gender,Worker.country
320,225.484,4,2,2,1,1,5,20.0,35,0.880000,...,0,0,0,0,0,0,1,2,1,20
321,75.758,5,2,2,1,1,4,5.0,26,0.703704,...,0,0,0,0,0,0,1,0,1,21
322,396.716,5,2,2,1,1,4,10.0,33,0.578947,...,0,0,0,0,0,0,2,3,1,22
323,899.377,4,3,2,1,1,5,5.0,33,1.000000,...,0,0,0,0,0,0,1,1,1,21
324,253.272,0,5,2,1,1,3,3.0,49,1.000000,...,0,0,0,0,0,0,0,4,0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,220.420,2,4,1,1,1,3,2.0,28,0.800000,...,0,0,0,0,0,0,1,0,1,21
2576,322.790,4,3,1,1,1,5,17.0,39,0.900000,...,0,0,0,0,0,0,2,3,1,21
2577,159.530,5,1,1,1,1,4,10.0,31,1.000000,...,0,0,0,0,0,0,1,3,1,35
2578,68.578,5,1,1,1,1,4,4.0,19,1.000000,...,0,0,0,0,0,0,1,4,1,22
2579,72.605,4,4,2,1,1,5,3.0,24,0.842105,...,0,0,0,0,0,0,1,0,1,7

In [205]:
from sklearn.ensemble import RandomForestClassifier

In [206]:
classifier = RandomForestClassifier()

In [207]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [211]:
from sklearn import metrics
scores = cross_val_score(clf, X, y, cv=5, scoring='precision_score')
scores

NameError: name 'cross_val_score' is not defined